# Matriks
## Definisi Matriks

 Matriks adalah kumpulan suatu bilangan yang terusun dalam baris dan kolom. matriks yaitu larik persegi panjang dari bilangan real atau kompleks

- Contoh :
 Matriks A berukuran 3 x 3 :

 $$A = \begin{pmatrix}
{11} & {12} & {13} \\
{21} & {22} & {23} \\
{31} & {32} & {33}
\end{pmatrix}$$

## Jenis jenis Matriks
1. Matriks Persegi
 Matriks dengan jumlah baris dan kolom sama (m = n).
 Contoh :
 $$A= \begin{pmatrix}
{1} & {3} \\
{2} & {5}
\end{pmatrix}$$



2. Vektor Baris
  Matriks dengan satu baris (1 x n).
  Contoh :
  
  $$ A = \begin{pmatrix} 1 & 2 & 3 \end{pmatrix}$$

3. Vektor kolom
  Matriks dengan satu kolom (𝑚×1).
  Contoh :

$$ A=  \begin{pmatrix}
1 \\
2 \\
3 \\
\end{pmatrix}$$

4. Diagonal Matriks Persegi
   Matriks persegi dengan semua entri di luar diagonal utama bernilai nol.

   Contoh:

$$ A = \begin{pmatrix}
1 &  3 \\
 2 & 5 \\
\end{pmatrix}$$

5. Matriks Nol :
   Matriks dengan semua entri bernilai 0.

   Contoh :

  $$ A= \begin{pmatrix}
0 & 0 \\
0 & 0
\end{pmatrix}$$

## Operasi Aritmatika
Operasi aritmatika matriks melibatkan beberapa operasi dasar yang dapat dilakukan pada matriks. Berikut adalah penjelasan mengenai operasi-operasi tersebut:


## Konsep Penjumlahan Matriks
  Penjumlahan matriks adalah operasi matematika yang menggabungkan dua matriks atau lebih menjadi satu matriks baru. Operasi ini hanya dapat dilakukan jika matriks-matriks yang akan dijumlahkan memiliki ukuran (ordo) yang sama.

###Syarat Penjumlahan Matriks

- Ordo Harus Sama: Dua matriks atau lebih hanya dapat dijumlahkan jika memiliki jumlah baris dan kolom yang sama. Misalnya, matriks 2x3 hanya bisa dijumlahkan dengan matriks 2x3 lainnya.

### Sifat-sifat Penjumlahan Matriks

  1. Komutatif: A + B = B + A
  2. Asosiatif: (A + B) + C = A + (B + C)
  3. Memiliki Matriks Identitas (Matriks Nol): A + 0 = A, di mana 0 adalah
     matriks nol (semua elemennya nol).

  Contoh : Misalkan kita memiliki dua matriks, A dan B, dengan ordo 2x2:

$$A = \begin{pmatrix}
{1} & {2} \\
{3} & {3}
\end{pmatrix}
 \quad
B = \begin{pmatrix}
{1} & {4} \\
{2} & {5}
\end{pmatrix}$$

$$
A + B = \begin{pmatrix}
{1} + {1} & {2} + {4} \\
{3} + {2} & {3} + {5}
\end{pmatrix}$$

$$
A + B = \begin{pmatrix}
{2} & {6} \\
{5} & {8}
\end{pmatrix}$$







In [3]:
import numpy as np

# Mendefinisikan matriks A dan B
A = np.array([[1, 2],
              [3, 3]])

B = np.array([[1, 4],
              [2, 5]])

# Melakukan penjumlahan matriks
C = A + B

# Menampilkan hasil
print("Matriks A:")
print(A)
print("\nMatriks B:")
print(B)
print("\nHasil penjumlahan A + B:")
print(C)

Matriks A:
[[1 2]
 [3 3]]

Matriks B:
[[1 4]
 [2 5]]

Hasil penjumlahan A + B:
[[2 6]
 [5 8]]


penyelesaian persamaan menggunakan invers matriks ( invers dicaari menggunakan baris erlementer)

## Konsep Perkalian Matriks
  Perkalian matriks adalah operasi matematika yang menggabungkan dua matriks menjadi satu matriks baru.

### Syarat Perkalian Matriks

 Jumlah Kolom Matriks Pertama Harus Sama dengan Jumlah Baris Matriks Kedua: Ini adalah syarat utama agar dua matriks dapat dikalikan. Jika matriks A berukuran mxn dan matriks B berukuran nxp, maka hasil perkalian matriks C akan berukuran mxp.

### Sifat-sifat Perkalian Matriks

- Tidak Komutatif: Secara umum, A x B ≠ B x A. Urutan perkalian matriks
  sangat penting.
- Asosiatif: (A x B) x C = A x (B x C)
- Distributif: A x (B + C) = A x B + A x C
- Memiliki Matriks Identitas: A x I = A, di mana I adalah matriks
  identitas.


 Contoh :



$$A = \begin{pmatrix}
{11} & {12} \\
{21} & {22}
\end{pmatrix}
B = \begin{pmatrix}
{11} & {12} \\
{21} & {22}
\end{pmatrix}$$


$$
A \cdot B = \begin{pmatrix}
{11} & {12} \\
{21} & {22}
\end{pmatrix} \cdot \begin{pmatrix}
{11} & {12} \\
{21} & {22}
\end{pmatrix}
$$

$$
= \begin{pmatrix}
{11}*{11} + {12}*{21} & {11}*{12} + {12}*{22} \\
{21}*{11} + {22}*{21} & {21}*{12} + {22}*{22}
\end{pmatrix}$$


In [5]:
import numpy as np

# Mendefinisikan matriks A dan B
A = np.array([[11, 12],
              [21, 22]])

B = np.array([[11, 12],
              [21, 22]])

# Melakukan perkalian matriks
C = np.dot(A, B)

# Atau bisa juga menggunakan operator @
# C = A @ B

# Menampilkan hasil
print("Matriks A:")
print(A)
print("\nMatriks B:")
print(B)
print("\nHasil perkalian A * B:")
print(C)

Matriks A:
[[11 12]
 [21 22]]

Matriks B:
[[11 12]
 [21 22]]

Hasil perkalian A * B:
[[373 396]
 [693 736]]


## Konsep Perkalian  Skalar
   Perkalian skalar matriks berarti mengalikan setiap elemen di dalam matriks dengan sebuah skalar.
   
   Jika kita memiliki matriks "A" dan skalar "k", maka hasil perkalian "kA" diperoleh dengan mengalikan setiap elemen di matriks "A" dengan "k".

   contoh :

   Misalkan kita memiliki matriks \( A \) dan skalar \( k \):

\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix}
Maka perkalian skalar \( k \) dengan matriks \( A \) adalah:

 \begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix} = \begin{pmatrix}
k \cdot a_{11} & k \cdot a_{12} \\
k \cdot a_{21} & k \cdot a_{22}
\end{pmatrix}

In [6]:
import numpy as np

# Mendefinisikan matriks A
A = np.array([[1, 2],
              [3, 4]])

# Mendefinisikan skalar k
k = 3

# Melakukan perkalian skalar
C = k * A

# Menampilkan hasil
print("Matriks A:")
print(A)
print("\nSkalar k:", k)
print("\nHasil perkalian skalar k * A:")
print(C)

Matriks A:
[[1 2]
 [3 4]]

Skalar k: 3

Hasil perkalian skalar k * A:
[[ 3  6]
 [ 9 12]]
